# image will be published to ghcr.io/<user>/<name>
name: box-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/blue-build/base-images/fedora-kinoite 
image-version: 43 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: dnf
    repos:
      files:
        - https://download.docker.com/linux/fedora/docker-ce.repo
    install:
      packages:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

  - type: systemd
    system:
      enabled:
      - docker.service

  - type: files
    files:
      - source: usr
        destination: /usr

  - type: dnf
    install:
      packages:
        - snapd
        - autofs
        - zsh
        - perl-FindBin
        - perl-IPC-Cmd
        - perl-File-Compare
        - perl-Time-Piece
        - mono-core
        - g++
        - python3.14-devel

  - type: dnf
    repos:
      files:
        - antigravity.repo
    install:
      packages:
        - antigravity

  - type: dnf
    group-install:
      packages:
        - "development-tools"

  - type: default-flatpaks
    configurations:
      - scope: system
        notify: true
        repo:
          title: Flathub (system)
          install:
            - com.discordapp.Discord
            - com.github.tchx84.Flatseal
            - io.github.flattool.Warehouse
            - io.missioncenter.MissionCenter

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
  - from-file: openrgb.yml 
  #- from-file: linux-arctis-manager.yml
  - from-file: sunshine.yml
  - type: script
    snippets:
      - "curl -fsSL https://tailscale.com/install.sh | sh"

  - type: systemd
    system:
      enabled:
        - var-home-creed-deeptank.mount
